### ISSUE TITLE
I have a question about the "-0.72" when using CC-human model to analysis the cut-in scenario

### ISSUE THREAD

**Issue by CCCCCarry** [ec-jrc/JRC-FSM#1]
![image](https://user-images.githubusercontent.com/84951994/183571277-f4382796-3b5f-4405-a61b-4c4ca0ecc5c1.png)
In the code "model.py", there is a "-0.72" in Line 50. 
I checked the UNECE Reg 157 Annex 4 - Appendix 3 and there is a figure also shows "0.72m"
![image](https://user-images.githubusercontent.com/84951994/183571584-6c22bc50-1579-4ce3-82b9-1b175eb5f499.png)
However, I couldn't figure out what the meaning of it. Could you help me explain its meaning？Thanks

**Comment by CCCCCarry** [comment]
I really appreciate the work you have done which has a great inspiration to me.

**Comment by eknabevcc** [comment]
I have the same problem. To my understanding the distance should represent the time it takes for the driver to be aware of the other vehicle passed the 0.375m wandering zone. According to "E/ECE/TRANS/505/Rev.3/Add.156 Annex 4 - Appendix 3", top of page 44:
`a.= lateral movement speed x Risk perception time [a] (0.4sec)`

I guess 0.72m implies lateral speed of `0.72m / 0.4s = 1.8m/s`. But I think the value should be calculated based on actual lateral speed, not applied as constant. For example, assuming that the perception time is constant, when the lateral movement is very slow that (a) distance becomes smaller than when lateral speed is high.

That about that. 

Then an observation:

There is another mentioning of the magic number 0.72. On page 10, section 5.2.5.2, in a criteria for when a collision with a cutting in vehicle should be avoided:
`(b) Provided that the lateral movement of the cutting in vehicle has been visible for a time of at least 0.72 seconds before the reference point for TTCLaneIntrusion is reached`

To my understanding it means that the cutting-in vehicle should have been visible to the driver for a duration of 0.72 seconds before passing the "magic line" becoming an intruder. Probably these two occurrences of the magic number `0.72` (one distance and one time) is just a coincidence.

**Comment by eknabevcc** [comment]
Actually I found a clarification in [ACSF-25-18 (Japan) proposal of the test threshfold for cutting in](https://wiki.unece.org/download/attachments/92013066/ACSF-25-18%20%28Japan%29%20proposal%20of%20the%20test%20threshfold%20for%20cutting%20in.pdf?api=v2) (page 6):
`[a:0.72m] = (Max lateral movement speed: 1.8m/s) x (Risk evaluation delay time: 0.4sec)` 

So basically I guess the idea is that 0.72m represent a worst case lateral movement (based on maximum lateral speed 1.8) during the time the (rear car) driver perceives that the cut-in is happening.

**Comment by CCCCCarry** [comment]
> Actually I found a clarification in [ACSF-25-18 (Japan) proposal of the test threshfold for cutting in](https://wiki.unece.org/download/attachments/92013066/ACSF-25-18%20%28Japan%29%20proposal%20of%20the%20test%20threshfold%20for%20cutting%20in.pdf?api=v2) (page 6): `[a:0.72m] = (Max lateral movement speed: 1.8m/s) x (Risk evaluation delay time: 0.4sec)`
> 
> So basically I guess the idea is that 0.72m represent a worst case lateral movement (based on maximum lateral speed 1.8) during the time the (rear car) driver perceives that the cut-in is happening.

Thanks for sharing the document. I guess so about the "0.72m" which is used to represent the ”critical condition”.
I also have another speculation. When the cutting-in vehicle reach the 0.72m, the distance betweeen the outside wheels and the line is 0.295m which is about 0.3m. It also match the UNECE R157 5.2.5.2.

`TTCLaneIntrusion = The TTC value, when the outside of the tyre of the intruding vehicle’s front wheel closest 
to the lane markings crosses a line 0.3 m beyond the outside edge of the visible lane marking to which the intruding vehicle is being drifted.`

**Comment by eknabevcc** [comment]
Ah, yes that's a good observation regarding wheel lateral position. 

However in my case with a more generic traffic simulator ([esmini](https://github.com/esmini/esmini)) the lateral distance from wheel to lane markings will vary, depending on vehicle dimensions and road lane widths. 

But when thinking about it, the 0.375 wide wandering area may be tuned for highways, which the ALKS is designed for. So the variation will probably not be significant.

**Comment by kostasmatt** [comment]
Thank you very much for your comments.

Regarding the 0.72m, it has been defined by the model developers are the "risk perception/judgment boundary" using the maximum lateral speed (https://www.grcc.vip/article-7247.html). It is indeed sort of a "worst case scenario".

The occurrence of 0.72s in another place is indeed just a coincidence as far as we understand.

I hope it helps.

**Comment by CCCCCarry** [comment]
> Thank you very much for your comments.
> 
> Regarding the 0.72m, it has been defined by the model developers are the "risk perception/judgment boundary" using the maximum lateral speed (https://www.grcc.vip/article-7247.html). It is indeed sort of a "worst case scenario".
> 
> The occurrence of 0.72s in another place is indeed just a coincidence as far as we understand.
> 
> I hope it helps.

It did solve my question, thanks!
